export const SCHEMATIC_SHEET_ID = "schematic_sheet_altium"

export const SCHEMATIC_UNIT_TO_MILLIMETERS = 10.16 / 1.1

export const SCHEMATIC_SHEET_INSET = 5 / SCHEMATIC_UNIT_TO_MILLIMETERS

export const SCHEMATIC_SHEET_WIDTH = 297 / SCHEMATIC_UNIT_TO_MILLIMETERS

export const SCHEMATIC_SHEET_HEIGHT = 210 / SCHEMATIC_UNIT_TO_MILLIMETERS

export const SCHEMATIC_SHEET_INNER_WIDTH =
  SCHEMATIC_SHEET_WIDTH - SCHEMATIC_SHEET_INSET * 2

export const SCHEMATIC_SHEET_INNER_HEIGHT =
  SCHEMATIC_SHEET_HEIGHT - SCHEMATIC_SHEET_INSET * 2
