export const INLINE_NET_LABEL_COLOR = "rgb(132, 0, 0)"

export const DEFAULT_INLINE_NET_LABEL_FONT_SIZE = 0.18

export const MIN_INLINE_NET_LABEL_FONT_SIZE = 0.1

export const INLINE_NET_LABEL_CHARACTER_WIDTH = 0.12

export const INLINE_NET_LABEL_HORIZONTAL_PADDING = 0.12
